[project]
name = "bpi-outages"
version = "0.1.0"
description = "Analyzing BPI outages from app log file"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "prefect>=3.1.11",
    "streamlit>=1.41.1",
]
